[build]
# 清除缓存
ignore_curl_headers = true
publish = "dist"
command = "pnpm run generate && prisma generate && pnpm run build"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
